-- LawMate main-page Oracle schema
-- Run as a user that has permission to create tables.

-- 1) Cases (for StatsChart)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE cases PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE cases (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_type   VARCHAR2(50) NOT NULL,
  title       VARCHAR2(200) NOT NULL,
  status      VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_cases_created_at ON cases(created_at);

-- 2) Precedents (for precedent search + AI recommendations)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE precedents PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE precedents (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category    VARCHAR2(50),
  title       VARCHAR2(300) NOT NULL,
  summary     CLOB,
  keywords    VARCHAR2(500),
  decided_at  DATE,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_precedents_title ON precedents(title);
CREATE INDEX idx_precedents_keywords ON precedents(keywords);
CREATE INDEX idx_precedents_decided_at ON precedents(decided_at);
